### PR TITLE
add FileInput component

### LINKED ISSUE #219: input[type="file"] Design Support
Right now the input type file works, but the design looks weird. Here is an example of how it looks:

Screen Shot 2019-03-20 at 4 55 25 PM

### PR DESCRIPTION
**Pull request by gesquinca**
resolves #219

### CODE REVIEW

**Comment by gesquinca** [comment]
@MikeLockz I think if we update or fix tests here we should be good to go.

**Comment by obernardovieira** [comment]
So, there's a Input and a Form.Input, where Form.Input is a pure <input> html tag, and works with onChange, although, the Input does not work with onChange. Can you guys help?

**Comment by zkalman** [comment]
@obernardovieira Thanks for your question, and sorry for the delay in response. We'll get you an answer shortly.

**Comment by gesquinca** [comment]
@obernardovieira I just made a fix on this PR #353

**Comment by gesquinca** [comment]
@obernardovieira The fix is live on the latest version of `rimble-ui`

**Pull request merged**
