### PR TITLE
Add SimpleAddress Component

### LINKED ISSUE #250: Simple Ethereum public address
As a user I want to see a simpler version of an Ethereum address in parts of a UI that don't have a lot of space.

Something like this:
Screenshot 2019-04-17 12 46 18

# Acceptance criteria

- Component accepts the following inputs:
    - Full address
- Component outputs a styled address in one of two formats
    - Full address
    - Truncated

- [ ] Documentation
- [ ] Tests

### PR DESCRIPTION
**Pull request by sublimatedpotato**
* required `address` string prop for the text to display
* accepts `truncate` bool prop to toggle whether the address provided is displayed in full or short
* uses `Text` component as base for uniform styling
* basic unit tests for sanity
* Adds documentation and stories for example usage of SimpleAddress

Resolves #250

### CODE REVIEW

**Comment by sublimatedpotato** [comment]
I do have export out of `App.js` and story docs queued up for this, as well, but wanted to get review of the actual component first. Happy to push it all now, too if that's preferred.

**Comment by gesquinca** [comment]
@sublimatedpotato you should push it all now so we can preview a branch deploy from here.

**Comment by sublimatedpotato** [comment]
@gesquinca everything should be available now. Let me know what corrections you might want made

**Comment by gesquinca** [comment]
Everything looks good on this implementation. We've deliberating on whether `SimpleAdress` and `PublicAddress` are good names for these components at the moment in order to proceed.

**Comment by sublimatedpotato** [comment]
Good to hear the code looks good!

My two cents would be that the component names `PublicAddress` and `SimpleAddress` don't intuitively reflect what they are, what differentiates them or when to use which. So I would argue in favor of some change. Maybe `SelectableAddress` and `TextAddress`?

**Comment by MikeLockz** [comment]
@sublimatedpotato - we have decided that to support future refactoring and implementing additional subcomponents we want to use the name **EthAddress** for this component and will use it as a base for future variations. Can you implement the name change?

**Comment by sublimatedpotato** [comment]
@MikeLockz sure thing. I believe what I just pushed should do the trick.

**Comment by MikeLockz** [comment]
@sublimatedpotato great job on the tests, the storybook, the example react app and the component! Thanks so much for contributing!

**Pull request merged**
